### ISSUE TITLE
Anime vs Smash

### ISSUE THREAD

**Issue by zedoax** [zedoax/jeffreys-ban#1]
So, Jeffrey's anime ~~addiction~~ watching habits are of growing concern.  He both reads manga and watches anime in excess during times with which he could be improving his productivity.  Much more than he usually plays smash.  So, to resolve this issue I propose an anime/manga amendment to his ban-list.

**Comment by jehling** [comment]
Understood. We will look into restricting Anime/Manga consumption outside of the hours of Late Night Animoon.

**Comment by EthanNichols** [comment]
I think before we restrict his ability to watch anime and read manga that we first restrict the rights for him playing games on the Nintendo switch.

**Comment by jehling** [comment]
As opposed to hard prohibition, I motion to produce a series of restrictions on the amount of time that can be invested within either video games or anime/manga. Removing these stress tools altogether would likely result in an overall decline in productivity on behalf of the contracted party. @zedoax  @EthanNichols

**Comment by zedoax** [comment]
@jehling is currently completing a fix for this issue
