### ISSUE TITLE
"within 4 days of" is ambiguous

### ISSUE THREAD

**Issue by sauriol** [zedoax/jeffreys-ban#18]
The phrasing in Section III Holiday Exception is ambiguous. The phrase "within 4 days of, as well as during, an acceptable holiday" can be interpreted as either a 9 or 7 day period centered around the holiday.

Changing Section III to say something like "Jeffrey is temporarily exempt from the terms of this contract for a X day period beginning ⌊X/2⌋ days before any acceptable holiday (enumerated below) and ending ⌊X/2⌋ days after the holiday" would make the exact terms of that section more clear.

**Comment by jehling** [comment]
Fixed with most recent pending PR.
