### ISSUE TITLE
Not legally binding

### ISSUE THREAD

**Issue by zthart** [zedoax/jeffreys-ban#2]
Write up an agreement for Jeff to sign such that he is legally bound to not do anything included in the list

**Comment by jehling** [comment]
Excellent idea. We will pursue this immediately.

**Comment by BionicPi** [comment]
Hmm. In most cases a contract would simply give us some weight in court, however that does not garuntee consequence. If, however, we present it as a prenuptial, and proceed to conduct a (legal) wedding, violation of the contract would be grounds for divorce, and thus loss of the tax benefits.

**Comment by zedoax** [comment]
I have added @jehling due to lack of progress on this matter

**Comment by jehling** [comment]
Done.
