### ISSUE TITLE
D-Pad Up

### ISSUE THREAD

**Issue by mfrancis95** [zedoax/jeffreys-ban#5]
According to Jeffrey, "I've been more productive since the ban, but my youtube feed just taunts me with Smash clips."

Purge his YouTube history and unsubscribe him from Smash-related channels. It'd be for the better.

**Comment by zedoax** [comment]
Interesting. However, it would be unbecoming to put this man under duress and erase his YouTube subscriptions.  Instead I propose a new ban on YouTube, so Jeffrey will consume less secondhand anime and smash-clips

**Comment by zedoax** [comment]
Stale issue
