### ISSUE TITLE
Progressive banning

### ISSUE THREAD

**Issue by BionicPi** [zedoax/jeffreys-ban#6]
While banning items serves primarily to enhance productivity and reduce time wasted, banning everything at once may result in reduced productivity, as the sudden expansion of 'free' time could result in listlessness. 

I would like to propose a progressive system of increasing bans, perhaps weekly, such that the bans both offer a looming negative punishment and reduce the likelihood of listlessness due to an abundance of time.

**Comment by zedoax** [comment]
This is interesting.  One addition I would like to suggest to this would be adding milestone goals.  If we combine a progressive ban with project milestones, it will entice Jeffrey to work on his major project little by little in order to avoid more severe 'ban hammers'

**Comment by jehling** [comment]
As it stands, we already require Jeffrey to re-affirm his acceptance of this contract with each major iteration. Agreeing to all changes henceforth would result in a heavily biased agreement that would be found unconscionable in court. As such, we will avoid this methodology.
