### ISSUE TITLE
Decline In Smash

### ISSUE THREAD

**Issue by Jflinchum** [zedoax/jeffreys-ban#7]
Ever since the recent Jeffrey Smash Ban of 2017, I couldn't help but notice the utter lack of any Smash and Smash happenings on floor. While it is important for Mr. Jeff to be productive, we cannot and should not allow it to affect Smash culture on floor.

I would like to propose a solution to this problem. Instead of avoiding Smash Bros. in its entirety, we should work towards a society where Smash can be played whilst Mr. Jeff can focus on his productivity. 

To that end, we could potentially lock Jeffrey in a sound-proof room with work to do, or something akin to that degree, while Smash Bros. is being played in the lounge. I believe Mr. Jeff would be happy knowing that his friends and peers are still enjoying Smash while he can achieve completion of his major project.

**Comment by zedoax** [comment]
This does seem to be a pressing concern.  However, please refrain from jumping to conclusions before an investigation is open to the matter.  We also claim no responsibility to any felonies (such as but not limited to: unlawful imprisonment) that you commit in your pursuit of this issue

**Comment by jehling** [comment]
Jeffrey is the sole party concerned within this contract. Any and all perceived externalities are beyond the scope of this agreement and, as such, are dismissed for lack of standing.
